name: Lint

on:
  pull_request_target:

permissions:
  pull-requests: write
  

jobs:
  textlint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: tsuyoshicho/action-textlint@v3
        with:
          github_token: ${{ secrets.github_token }}
