name: Lint

on:
  pull_request_target:

permissions:
  pull-requests: write

jobs:
  textlint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
          submodules: true
      - name: Setup node/npm
        uses: actions/setup-node@v1
        with:
          node-version: '15'
      - uses: tsuyoshicho/action-textlint@v3
        with:
          fail_on_error: true
